const SETS = [
  {id:'A', name:'Paper Quiz #1 · 1st Semester 2025', pages:'1–2', blurb:'Written delay/HTTP problems, layers, matching, Wireshark capture, DNS records.'},
  {id:'B', name:'Paper Quiz · True/False, MCQ & delay problems', pages:'3–5', blurb:'8 true/false, 6 multiple choice, a three-link delay problem and a DNS + HTTP timing problem.'},
  {id:'C', name:'LMS Quiz #1 · graded review', pages:'6–11', blurb:'Blackboard review screenshots: three-link problem, shared-link utilization, caching, delay matching.'},
  {id:'D', name:'LMS Quiz #1 · version 2', pages:'12–18', blurb:'Authoritative DNS, router layers, three-link problem, header matching, HTTP/1.0 RTTs.'},
  {id:'E', name:'LMS Quiz #1 · version 3', pages:'19–31', blurb:'Delay definitions, data units per layer, DNS hierarchy, conditional GET.'},
  {id:'F', name:'Paper Quiz · throughput, MCQ & DNS timing', pages:'32–33', blurb:'Bottleneck throughput, HTTP status codes, DNS record types, DNS + HTTP delay.'},
  {id:'H', name:'LMS Quiz · version 4', pages:'37–42', blurb:'Bandwidth, TDM, a link-3 / Router 2 variant of the three-link problem, TDM vs FDM.'},
  {id:'G', name:'Later chapters · network layer & TCP', pages:'34–36', blurb:'IPv4/IPv6, longest-prefix match, TCP Reno/Tahoe, subnetting and NAT. Not in your Chapter 1–2 slides.'}
];

const S1 = n => `Chapter 1 slides · slide ${n}`;
const S2 = n => `Chapter 2 slides · slide ${n}`;
const OUT = 'Not in your Chapter 1–2 slides or Tutorial 1. Answered from the same textbook these slides come from (Kurose & Ross, <i>Computer Networking: A Top-Down Approach</i>, 8th ed.)';

const THREE_LINK = `Two hosts A and B are connected by 3 links (Host A –Link1– Router 1 –Link2– Router 2 –Link3– Host B). Link lengths: <b>1500 km, 5000 km, 1000 km</b>. Transmission rates: <b>10 Mbps, 30 Mbps, 25 Mbps</b>. Propagation speed 2×10<sup>8</sup> m/s. Packet length <b>4000 bits</b>. Answer in seconds.`;

const Q = [
/* ================= SET A ================= */
{id:'A1a', set:'A', page:'1', ch:'1', type:'written',
 q:`Two routers A and B are connected by a link with transmission rate <b>100 Mbps</b> and length <b>2000 km</b>. The propagation speed is <b>2.5×10<sup>6</sup> m/s</b>. You send a packet of <b>200 Kbits</b> from A to B. What is the <b>propagation delay</b>?`,
 answer:`d<sub>prop</sub> = d / s = 2,000,000 m ÷ 2.5×10<sup>6</sup> m/s = <b>0.8 s (800 ms)</b>`,
 exp:`Propagation delay depends only on the link length and the propagation speed, so the 100 Mbps rate and the 200 Kbit packet size are distractors (they would give the transmission delay, L/R = 2 ms). Convert km to m first: 2000 km = 2×10<sup>6</sup> m.`,
 note:`The paper prints 2.5×10<sup>6</sup> m/s. If your instructor meant the usual 2.5×10<sup>8</sup> m/s, the answer would be 2×10<sup>6</sup> ÷ 2.5×10<sup>8</sup> = 0.008 s (8 ms).`,
 src:[S1(50)+' — d<sub>prop</sub> = d/s', 'Tutorial 1 · Chapter 1, Q1 and Q3 use the same formula']},

{id:'A1b', set:'A', page:'1', ch:'2', type:'written',
 q:`A network has <b>750 requests per second</b>, each request is <b>2 KB</b> (2 kilobytes), and the link capacity is <b>10 Mbps</b>. What is the traffic intensity (utilization) of the link?`,
 answer:`Traffic intensity = La / R = (750 × 16,000 bits) / 10×10<sup>6</sup> bps = 12 Mbps / 10 Mbps = <b>1.2</b>`,
 exp:`First turn bytes into bits: 2 KB = 2 × 1000 × 8 = 16,000 bits. The arrival rate of bits is 750 × 16,000 = 12,000,000 bps = 12 Mbps. Divide by the link rate. Because the value is greater than 1, more work arrives than the link can serve, so the queue grows without limit and the average queueing delay goes to infinity.`,
 note:`If you use 1 KB = 1024 bytes you get 12.29 Mbps / 10 Mbps ≈ 1.23. Either way it is above 1.`,
 src:[S1(53)+' — traffic intensity = La/R; La/R > 1 means average delay is infinite', S2(37)+' — access link utilization example', 'Tutorial 1 · Chapter 2, Q2a (750 requests/s, same method, answer 75%)']},

{id:'A1c', set:'A', page:'1', ch:'2', type:'written',
 q:`How many RTTs are needed to download a web page that consists of a base page and <b>5 objects</b>, if the connection is <b>persistent and without pipelining</b>?`,
 answer:`1 RTT (TCP setup) + 1 RTT (base HTML) + 5 × 1 RTT (one per object) = <b>7 RTT</b>`,
 exp:`Persistent HTTP opens the TCP connection once and keeps it open, so only the first object pays the extra RTT for the handshake. Without pipelining, the client waits for each response before sending the next request, so each of the 5 objects costs one more RTT.`,
 src:[S2(20)+' — persistent vs non-persistent HTTP', S2(23)+' — one RTT to initiate TCP, one RTT per request/response', S2(24)+' — persistent HTTP keeps the connection open', 'Tutorial 1 · Chapter 2, Q1c (page + 3 images, persistent without pipelining = 5 RTT)']},

{id:'A2-1', set:'A', page:'1', ch:'1', type:'match',
 q:`For each device, determine the <b>highest layer</b> it works on.`,
 rows:['Router','Server','Link-layer switch','Smartphone'],
 choices:['Application layer','Transport layer','Network layer','Link layer','Physical layer'],
 ans:[2,0,3,0],
 answer:`Router → Network · Server → Application · Link-layer switch → Link · Smartphone → Application`,
 exp:`End systems (hosts) such as servers and smartphones run applications, so they implement all five layers. A router implements network, link and physical, so its highest layer is network. A link-layer switch implements only link and physical.`,
 src:[S1(69)+' — encapsulation end-to-end view: router has network/link/physical, switch has link/physical', S1(64)+' — the five-layer Internet stack', S2(5)+' — network-core devices do not run user applications']},

{id:'A2-2', set:'A', page:'2', ch:'1', type:'match',
 q:`Match each networking concept with its correct description.`,
 rows:['Throughput','Circuit switching','Packet switching','Propagation delay'],
 choices:['1. Resources (bandwidth, buffers) are reserved end-to-end','2. Time for one bit to travel across the physical link','3. The average rate at which bits are successfully delivered over a link','4. Packets may take different routes, causing variable delay'],
 ans:[2,0,3,1],
 answer:`Throughput → 3 · Circuit switching → 1 · Packet switching → 4 · Propagation delay → 2`,
 exp:`Throughput is the rate at which bits get from sender to receiver. Circuit switching reserves end-to-end resources for the call. In packet switching each packet is forwarded hop by hop and can be queued, so delay varies. Propagation delay is d/s, the time for a bit to cross the link.`,
 src:[S1(56)+' — throughput definition', S1(33)+' — circuit switching: end-end resources reserved', S1(25)+' and '+S1(36)+' — packet switching, congestion and variable delay', S1(50)+' — propagation delay']},

{id:'A2-3a', set:'A', page:'2', ch:'2', type:'written',
 q:`The following was captured by Wireshark:`,
 code:`HTTP/1.1 200 OK\\r\\n
Date: Tue, 23 SEP 2025 17:11:13 GMT\\r\\n
Server: Apache/2.4.6 (CentOS) OpenSSL/1.0.2k-fips PHP/5.4.16 mod_perl/2.0.11 Perl/v5.16.3\\r\\n
Content-Length: 209\\r\\n
Keep-Alive: timeout=5, max=100\\r\\n
Connection: Keep-Alive\\r\\n
Content-Type: text/html; charset=iso-8859-1\\r\\n
\\r\\n`,
 q2:`(a) Was the server able to successfully find the file or not? Say where in the message you found the answer.`,
 answer:`<b>Yes.</b> The status line <code>HTTP/1.1 200 OK</code> says the request succeeded.`,
 exp:`The first line of a response is the status line: protocol version, status code, status phrase. Code 200 means "request succeeded, requested object later in this message". If the file were missing the server would send 404 Not Found.`,
 note:`The question calls this the GET message, but what is shown is the server's <i>response</i> (it starts with a status line, not a GET request line).`,
 src:[S2(28)+' — HTTP response message, status line', S2(29)+' — 200 OK vs 404 Not Found']},

{id:'A2-3b', set:'A', page:'2', ch:'2', type:'written',
 q:`(Same capture as above.) Is the connection non-persistent or persistent? Say how you got your answer.`,
 answer:`<b>Persistent.</b> The header lines <code>Connection: Keep-Alive</code> and <code>Keep-Alive: timeout=5, max=100</code> show the server will keep the TCP connection open.`,
 exp:`With non-persistent HTTP the server closes the TCP connection after one object (it would send <code>Connection: close</code>). Here the server says it keeps the connection alive for 5 seconds and up to 100 more requests. The version HTTP/1.1 also uses persistent connections by default.`,
 src:[S2(20)+' — two types of HTTP connections', S2(24)+' — persistent HTTP (HTTP 1.1): server leaves connection open', S2(25)+' — "Connection: keep-alive" header line']},

{id:'A2-4', set:'A', page:'2', ch:'2', type:'written',
 q:`For each DNS record type, fill in what the <b>Name</b> and <b>Value</b> fields hold: <b>NS</b> and <b>CNAME</b>.`,
 answer:`<table class="mini"><tr><th>Type</th><th>Name</th><th>Value</th></tr>
<tr><td>NS</td><td>A domain, e.g. <code>networkutopia.com</code></td><td>Hostname of the authoritative name server for that domain, e.g. <code>dns1.networkutopia.com</code></td></tr>
<tr><td>CNAME</td><td>An alias name, e.g. <code>www.ibm.com</code></td><td>The canonical (real) name, e.g. <code>servereast.backup2.ibm.com</code></td></tr></table>`,
 exp:`A DNS resource record is (name, value, type, ttl). The meaning of name and value depends on the type. NS points a domain to its authoritative server; CNAME maps an alias to the real hostname.`,
 src:[S2(54)+' — DNS records: NS, CNAME, A, MX', S2(57)+' — example (networkutopia.com, dns1.networkutopia.com, NS)']},

/* ================= SET B ================= */
{id:'B1-1', set:'B', page:'3', ch:'1', type:'mcq', opts:['True','False'], ans:0,
 q:`Packet switching is based on resource sharing between all users; it is also more efficient than circuit switching in terms of resource utilization.`,
 exp:`Packet switching shares link capacity on demand. In the slide example a 1 Gb/s link supports only 10 users with circuit switching, but 35 users with packet switching with very small probability of overload.`,
 src:[S1(35)+' — 10 users vs 35 users', S1(36)+' — packet switching: resource sharing, great for bursty data']},
{id:'B1-2', set:'B', page:'3', ch:'1', type:'mcq', opts:['True','False'], ans:1,
 q:`<b>Routing</b> is the local action of moving arriving packets from a router's input link to the appropriate output link, while <b>forwarding</b> is the global action of determining the source-destination paths taken by packets.`,
 exp:`The definitions are swapped. <b>Forwarding</b> is the local action (input link → output link, using the forwarding table). <b>Routing</b> is the global action of determining source-to-destination paths.`,
 src:[S1(26)+' — Two key network-core functions']},
{id:'B1-3', set:'B', page:'3', ch:'1', type:'mcq', opts:['True','False'], ans:1,
 q:`Wireless links are the best transmission media in terms of transmission rate and reliability.`,
 exp:`Fiber optic cable is the best on both counts: 10s–100s Gbps, low error rate, immune to electromagnetic noise. Wireless radio suffers from reflection, obstruction and interference, and WiFi runs at 10–100s Mbps.`,
 src:[S1(22)+' — fiber optic cable', S1(23)+' — wireless radio and its propagation problems']},
{id:'B1-4', set:'B', page:'3', ch:'1', type:'mcq', opts:['True','False'], ans:1,
 q:`In the context of networking model layers, <b>switches</b> work on the three lower layers.`,
 exp:`A link-layer switch implements only the <b>link and physical</b> layers (two layers). It is the <b>router</b> that implements the three lower layers (network, link, physical).`,
 src:[S1(69)+' — switch: link + physical; router: network + link + physical']},
{id:'B1-5', set:'B', page:'3', ch:'1', type:'mcq', opts:['True','False'], ans:1,
 q:`The main function of the network layer in the OSI reference model is process-to-process data transfer.`,
 exp:`Process-to-process data transfer is the <b>transport</b> layer's job (TCP, UDP). The network layer routes datagrams from source host to destination host.`,
 src:[S1(64)+' — layer functions', S1(72)+' — the seven-layer OSI model shares these lower layers']},
{id:'B1-6', set:'B', page:'3', ch:'2', type:'mcq', opts:['True','False'], ans:0,
 q:`Streaming video and audio applications are loss-tolerant applications, meaning they accept some loss of their data.`,
 exp:`The transport-requirements table lists streaming audio/video as loss-tolerant, unlike file transfer, e-mail and web documents, which need no loss.`,
 src:[S2(13)+' — transport service requirements of common apps', S2(12)+' — "other apps (e.g., audio) can tolerate some loss"']},
{id:'B1-7', set:'B', page:'3', ch:'1', type:'mcq', opts:['True','False'], ans:1,
 q:`The main function of the application layer is to establish an end-to-end connection between applications.`,
 exp:`The application layer supports network applications (HTTP, SMTP, DNS) by exchanging messages. Setting up a connection between processes is done by the <b>transport</b> layer: TCP is connection-oriented.`,
 src:[S1(64)+' — application layer: supporting network applications', S2(14)+' — TCP: connection-oriented, setup required']},
{id:'B1-8', set:'B', page:'3', ch:'1', type:'mcq', opts:['True','False'], ans:0,
 q:`In circuit switching, Frequency Division Multiplexing (FDM) and Time Division Multiplexing (TDM) are two approaches for implementing this technique.`,
 exp:`The slides present FDM (each call gets its own frequency band) and TDM (each call gets periodic time slots) as the two ways to build circuits on a link.`,
 src:[S1(34)+' — Circuit switching: FDM and TDM']},

{id:'B2-1', set:'B', page:'3', ch:'1', type:'mcq',
 q:`What is the packet delay component computed as the time spent waiting in packet buffers for link transmission?`,
 opts:['Queueing delay','Propagation delay','Processing delay','Transmission delay'], ans:0,
 exp:`d<sub>queue</sub> is the time a packet waits at the output link for transmission; it depends on how congested the router is.`,
 src:[S1(49)+' — d<sub>queue</sub>: time waiting at output link for transmission', S1(47)+' — packets in buffers = queueing delay']},
{id:'B2-2', set:'B', page:'3', ch:'1', type:'mcq', also:'29',
 q:`Which of the definitions below describes what is meant by the term <b>"encapsulation"</b>?`,
 opts:['Receiving a "packet" from the layer below, extracting the payload field, and after some internal actions possibly delivering that payload to an upper layer protocol.','Starting a transport layer timer for a transmitted segment, and then if an ACK segment isn\'t received before the timeout, placing that segment in a retransmission queue.','Computing the sum of all of the bytes within a packet and placing that value in the packet header field.','Taking data from the layer above, adding header fields appropriate for this layer, and then placing the data in the payload field of the "packet" for that layer.','Determining the name of the destination host, translating that name to an IP address and then placing that value in a packet header field.'],
 ans:3,
 exp:`Each layer takes what the layer above gives it and wraps it with its own header: the transport layer adds H<sub>t</sub> to the message M to make a segment, the network layer adds H<sub>n</sub> to make a datagram, and so on. Option A describes the reverse (decapsulation).`,
 src:['Chapter 1 slides · slides 65–67 — Services, layering and encapsulation']},
{id:'B2-3', set:'B', page:'3–4', ch:'1', type:'mcq',
 q:`Within the TCP/IP model layers, where does a <b>router</b>, functioning as a computer networking device, primarily operate?`,
 opts:['The three upper layers','In application layer','The three lower layers','Physical layer'], ans:2,
 exp:`A router implements the network, link and physical layers, the three lower layers of the five-layer stack. It does not run transport or application layers for the traffic it forwards.`,
 src:[S1(69)+' — router: network / link / physical']},
{id:'B2-4', set:'B', page:'4', ch:'1', type:'mcq',
 q:`Which of these is <b>not</b> a guided medium?`,
 opts:['Fiber optical cable','Coaxial cable','Wireless LAN','Copper wire'], ans:2,
 exp:`Guided media carry signals in solid media: copper, fiber, coax. Unguided media let signals propagate freely, e.g. radio. A wireless LAN uses radio.`,
 src:[S1(21)+' — guided vs unguided media', S1(23)+' — wireless radio, WiFi']},
{id:'B2-5', set:'B', page:'4', ch:'2', type:'mcq', also:'28',
 q:`What is the purpose of the <b>conditional</b> HTTP GET request message?`,
 opts:['To allow a server to only send the requested object to the client if the client has never requested that object before.','To allow a server to only send the requested object to the client if the server is not overloaded.','To allow a server to only send the requested object to the client if the client is authorized to receive that object.','To allow a server to only send the requested object to the client if this object has changed since the server last sent this object to the client.'],
 ans:3,
 exp:`The goal of conditional GET is: don't send the object if the cache already has an up-to-date copy. The client includes <code>If-modified-since: &lt;date&gt;</code>; the server replies <code>304 Not Modified</code> with no object if nothing changed, or <code>200 OK</code> with the object if it was modified.`,
 src:[S2(41)+' — Conditional GET']},
{id:'B2-6', set:'B', page:'4', ch:'2', type:'mcq',
 q:`Which response code in an HTTP response message means that the request is bad and not understood by the server?`,
 opts:['200','404','400','505'], ans:2,
 exp:`400 Bad Request: "request msg not understood by server". 200 is OK, 404 is Not Found, 505 is HTTP Version Not Supported.`,
 src:[S2(29)+' — HTTP response status codes']},

{id:'B3-1', set:'B', page:'4', ch:'1', type:'mcq', fig:'links3',
 q:`A client sends packets of length L bytes over link 1, link 2 and link 3 to the server. Packet length is <b>32000 bytes</b>, propagation speed is 3×10<sup>8</sup> m/s.<br><br>Compute the <b>transmission delay at link 1</b>.`,
 opts:['0.128 msec','0.032 msec','0.256 msec','32 sec','256 sec'], ans:2,
 exp:`L = 32,000 bytes × 8 = 256,000 bits. Link 1 rate R = 1000 Mbps = 10<sup>9</sup> bps.<br>d<sub>trans</sub> = L/R = 256,000 / 10<sup>9</sup> = 0.000256 s = <b>0.256 msec</b>. Option B (0.032 msec) is what you get if you forget to convert bytes to bits.`,
 src:[S1(50)+' — d<sub>trans</sub> = L/R', S1(30)+' — one-hop numerical example']},
{id:'B3-2', set:'B', page:'4', ch:'1', type:'mcq', fig:'links3',
 q:`(Same figure.) Compute the <b>propagation delay for link 2</b>.`,
 opts:['0.01667 msec','0.01667 sec','0.5 sec','0.5 msec','0.05 msec'], ans:1,
 exp:`Link 2 length = 5000 km = 5×10<sup>6</sup> m.<br>d<sub>prop</sub> = d/s = 5×10<sup>6</sup> / 3×10<sup>8</sup> = <b>0.01667 s</b> (16.67 ms). The value is the same number as option A, but A has the wrong unit.`,
 src:[S1(50)+' — d<sub>prop</sub> = d/s']},
{id:'B3-3', set:'B', page:'5', ch:'1', type:'mcq', fig:'links3',
 q:`(Same figure.) What is the maximum end-to-end achievable data rate the client can send to the server?`,
 opts:['1000 Mbps','100 Mbps','10 Mbps','1110 Mbps','1 Mbps'], ans:2,
 exp:`End-to-end throughput is limited by the slowest link on the path, the bottleneck: min(1000, 10, 100) Mbps = <b>10 Mbps</b> (link 2).`,
 src:[S1(57)+' — bottleneck link', S1(58)+' — end-end throughput = min of the link rates']},
{id:'B3-4', set:'B', page:'5', ch:'1', type:'mcq', fig:'links3',
 q:`Suppose the client sends data at the maximum achievable data rate. What is the utilization (U) of <b>link 3</b>?`,
 opts:['U = 1','U = 100','U = 0.10','U = 10','U = 1000'], ans:2,
 exp:`The client can only push 10 Mbps end to end (previous question), so link 3 carries 10 Mbps out of its 100 Mbps capacity: U = arrival rate of bits / link rate = 10 / 100 = <b>0.10</b>.`,
 src:[S1(53)+' — traffic intensity La/R (arrival rate of bits / service rate)', S2(37)+' — "access link utilization" computed as data rate / link rate']},
{id:'B3-5', set:'B', page:'5', ch:'1', type:'written', fig:'links3',
 q:`Suppose the total delays for links 1, 2, 3 are <b>10, 20, 30 msec</b> respectively. What is the end-to-end delay from the client to the server?`,
 answer:`End-to-end delay = 10 + 20 + 30 = <b>60 msec</b>`,
 exp:`Each hop adds its own nodal delay (processing + queueing + transmission + propagation). The packet crosses the three links one after another (store-and-forward), so the end-to-end delay is the sum of the per-link delays.`,
 src:[S1(49)+' — d<sub>nodal</sub> per hop', S1(30)+' — store and forward', 'Tutorial 1 · Chapter 1, Q4 (adding per-hop delays along a path)']},

{id:'B4-1', set:'B', page:'5', ch:'2', type:'written', fig:'dnshttp',
 q:`You click a link to a Web page. The IP address isn't cached on your host, so a DNS lookup is needed. Only one DNS server (the local DNS cache) is visited, with RTT<sub>0</sub> = <b>3 ms</b>. The page has exactly one object (a small HTML file). RTT between the host and the Web server: RTT<sub>HTTP</sub> = <b>27 ms</b>.<br><br>(1) Assuming zero transmission time for the HTML object, how much time (in msec) elapses from the click until the client receives the object?`,
 answer:`RTT<sub>0</sub> + 2·RTT<sub>HTTP</sub> = 3 + 2(27) = <b>57 ms</b>`,
 exp:`First the DNS query to the local DNS server: 3 ms. Then HTTP needs 1 RTT to set up the TCP connection and 1 RTT for the request and response: 2 × 27 = 54 ms. Transmission time is zero.`,
 src:[S2(50)+' — the host sends its DNS query to the local DNS server', S2(23)+' — non-persistent HTTP response time = 2RTT + transmission time']},
{id:'B4-2', set:'B', page:'5', ch:'2', type:'written', fig:'dnshttp',
 q:`(2) The HTML object now references <b>10 very small objects</b> on the same server. Neglecting transmission times, how much time elapses until the base object and all 10 objects are received, with <b>non-persistent HTTP and no parallel TCP connections</b>?`,
 answer:`3 + 2(27) + 10 × 2(27) = 3 + 54 + 540 = <b>597 ms</b>`,
 exp:`Non-persistent HTTP needs 2 RTTs per object (new TCP connection + request/response). The base page costs 2 RTTs, then each of the 10 objects costs another 2 RTTs one after another.`,
 src:[S2(22)+' — "steps 1–5 repeated for each of 10 jpeg objects"', S2(24)+' — non-persistent HTTP requires 2 RTTs per object', 'Tutorial 1 · Chapter 2, Q1b (non-persistent, no parallel connections)']},
{id:'B4-3', set:'B', page:'5', ch:'2', type:'written', fig:'dnshttp',
 q:`(3) Same 10 objects, but the client supports up to <b>5 parallel TCP connections</b> with <b>non-persistent HTTP</b>.`,
 answer:`3 + 2(27) + 2 × 2(27) = 3 + 54 + 108 = <b>165 ms</b>`,
 exp:`After the base page (DNS + 2 RTTs), the 10 objects are fetched 5 at a time, so two rounds. Each round uses new non-persistent connections, so each costs 2 RTTs.`,
 src:[S2(24)+' — browsers open multiple parallel TCP connections', S2(23)+' — 2 RTTs per non-persistent fetch']},
{id:'B4-4', set:'B', page:'5', ch:'2', type:'written', fig:'dnshttp',
 q:`(4) Same 10 objects, up to <b>5 parallel TCP connections</b>, with <b>persistent HTTP</b>.`,
 answer:`3 + 2(27) + 2 × 27 = 3 + 54 + 54 = <b>111 ms</b>`,
 exp:`DNS (3 ms) + 2 RTTs for the base page. With persistent HTTP the connections stay open, so each object costs only 1 RTT (request + response), with no new TCP handshake. The 10 objects go out 5 at a time over the 5 parallel connections, so 2 rounds × 27 ms = 54 ms.`,
 note:`The limit of 5 parallel connections only matters if each connection carries one request at a time, which is why the rounds are counted. If your instructor instead assumes pipelining (all 10 requests sent back-to-back), the slide says this takes "as little as one RTT for all the referenced objects": 3 + 54 + 27 = 84 ms.`,
 src:[S2(24)+' — persistent HTTP: server leaves connection open; subsequent requests sent over the open connection', S2(23)+' — 1 RTT per request/response once the connection exists']},
{id:'B4-5', set:'B', page:'5', ch:'2', type:'mcq', fig:'dnshttp',
 q:`(5) What's the fastest method we've explored?`,
 opts:['Nonpersistent-serial','Nonpersistent-parallel','Persistent-parallel'], ans:2,
 exp:`From parts 2–4: non-persistent serial = 597 ms, non-persistent parallel = 165 ms, persistent parallel = 111 ms (84 ms with pipelining). Persistent connections remove the TCP setup RTT for every object, and parallel connections overlap the requests.`,
 src:[S2(24)+' — persistent HTTP cuts response time']},

/* ================= SET C ================= */
{id:'C4a', set:'C', page:'6', ch:'1', type:'written', fig:'hostab',
 q:THREE_LINK+`<br><br>(a) Transmission delay of <b>link 2</b> = ? seconds`,
 answer:`d<sub>trans</sub> = L/R = 4000 / 30×10<sup>6</sup> = <b>1.333×10<sup>-4</sup> s (0.000133 s)</b>`,
 exp:`Transmission delay uses the packet length and the rate of the link being transmitted onto. Link 2 runs at 30 Mbps.`,
 src:[S1(50)+' — d<sub>trans</sub> = L/R']},
{id:'C4b', set:'C', page:'6', ch:'1', type:'written', fig:'hostab',
 q:`(Same setup.) (b) What is the <b>total delay of link 2</b>? (seconds)`,
 answer:`d<sub>trans</sub> + d<sub>prop</sub> = 0.000133 + (5×10<sup>6</sup> / 2×10<sup>8</sup>) = 0.000133 + 0.025 = <b>0.025133 s</b>`,
 exp:`With no processing or queueing delay given, the delay for a link is transmission plus propagation. Propagation: 5000 km = 5×10<sup>6</sup> m, divided by 2×10<sup>8</sup> m/s gives 0.025 s.`,
 src:[S1(49)+' and '+S1(50).replace('Chapter 1 slides · ','')+' — d<sub>nodal</sub> = d<sub>proc</sub> + d<sub>queue</sub> + d<sub>trans</sub> + d<sub>prop</sub>']},
{id:'C4c', set:'C', page:'6', ch:'1', type:'written', fig:'hostab',
 q:`(Same setup.) (c) If the average packet arrival rate at <b>Router 1</b> is <b>10 packets/s</b>, compute the traffic intensity at Router 1.`,
 answer:`La/R = (10 × 4000) / 30×10<sup>6</sup> = <b>0.00133</b> (1.33×10<sup>-3</sup>)`,
 exp:`Packets queue at a router's <i>output</i> link. Router 1 sends packets toward B on link 2, so R is link 2's rate, 30 Mbps. a = 10 packets/s, L = 4000 bits.`,
 src:[S1(53)+' — traffic intensity = La/R', S1(31)+' — queue of packets waiting for transmission over output link']},
{id:'C3', set:'C', page:'8', ch:'1', type:'written', fig:'servers4',
 q:`Four servers are connected to four clients over four three-hop paths. The pairs share a common middle hop of capacity <b>R = 300 Mbps</b>. Each server link has <b>R<sub>S</sub> = 50 Mbps</b>; each client link has <b>R<sub>C</sub> = 90 Mbps</b>.<br><br>Assuming the servers all send at their maximum possible rate, what is the utilization of the <b>shared link</b> (capacity R)? Give 1.00 or 0.xx.`,
 answer:`Each pair gets min(R<sub>S</sub>, R/4, R<sub>C</sub>) = min(50, 75, 90) = 50 Mbps. Shared link carries 4 × 50 = 200 Mbps, so utilization = 200 / 300 = <b>0.67</b>`,
 exp:`The server links are the bottleneck, so each server can push at most 50 Mbps. Four flows together put 200 Mbps onto the 300 Mbps middle link.`,
 src:[S1(58)+' — per-connection throughput = min(R<sub>c</sub>, R<sub>s</sub>, R/N)', S1(53)+' — utilization / traffic intensity']},
{id:'C2', set:'C', page:'9', ch:'1', type:'written',
 q:`An internet <b>switch</b> involves the following layers of the TCP/IP layers:`,
 answer:`<b>Link (data link) and physical layers</b>`,
 exp:`A link-layer switch only looks at link-layer frames. In the end-to-end encapsulation figure, the switch's stack has just the link and physical layers, while the router also has the network layer.`,
 note:`The screenshot doesn't show the answer choices; pick the option that says "physical and data link layers".`,
 src:[S1(69)+' — switch: link + physical']},
{id:'C6', set:'C', page:'7', ch:'2', type:'written',
 q:`In HTTP web browser caching, HTTP local web server caching, and local DNS caching, a user benefits from finding a nearby copy. In which forms of caching does a user benefit not only from its own recent requests but <i>also from recent requests made by other users</i>?`,
 answer:`<b>HTTP local web server caching (the institution's web cache / proxy) and local DNS caching.</b> Browser caching only helps the user who made the request.`,
 exp:`A local web cache is shared: everyone in the institution points their browser at it, so an object fetched by one user is served from the cache to the next. The local DNS server is also shared by all hosts in the ISP or institution, and it caches every name-to-address mapping it learns. A browser cache lives on one user's own machine.`,
 note:`This was graded 0.5/1 on the screenshot, which suggests the full answer needs both shared caches.`,
 src:[S2(35)+' and '+S2(36).replace('Chapter 2 slides · ','')+' — Web caches: user configures browser to point to a local cache', S2(50)+' — local DNS server answers from its cache', S2(53)+' — any name server caches mappings it learns']},
{id:'C8', set:'C', page:'10', ch:'1', type:'match',
 q:`Match the description of each component of packet delay to its name.`,
 rows:['Time needed to perform an integrity check, look up packet information in a local table and move the packet from an input link to an output link in a router.','Time spent waiting in packet buffers for link transmission.','Time spent transmitting the packet\'s bits into the link.','Time needed for bits to physically propagate through the transmission medium from one end of a link to the other.'],
 choices:['Processing delay','Queueing delay','Transmission delay','Propagation delay'],
 ans:[0,1,2,3],
 answer:`Processing → Queueing → Transmission → Propagation (in the order listed)`,
 exp:`d<sub>proc</sub> checks bit errors and determines the output link. d<sub>queue</sub> is waiting at the output link. d<sub>trans</sub> = L/R pushes the bits out. d<sub>prop</sub> = d/s is travel time on the wire.`,
 src:[S1(49)+' — d<sub>proc</sub>, d<sub>queue</sub>', S1(50)+' — d<sub>trans</sub>, d<sub>prop</sub>']},

/* ================= SET D ================= */
{id:'D1', set:'D', page:'18', ch:'1', type:'written', fig:'servers4',
 q:`Same four-server scenario (R = 300 Mbps shared, R<sub>S</sub> = 50 Mbps, R<sub>C</sub> = 90 Mbps). Assuming the servers all send at their maximum rate, what is the utilization of the <b>client links</b> (capacity R<sub>C</sub>)? Give 1.00 or 0.xx.`,
 answer:`Each client link carries 50 Mbps of its 90 Mbps: 50 / 90 = <b>0.56</b>`,
 exp:`Each flow is limited to min(50, 300/4, 90) = 50 Mbps by its server link. That 50 Mbps arrives on the client link, which can carry 90 Mbps.`,
 src:[S1(58)+' — per-connection throughput = min(R<sub>c</sub>, R<sub>s</sub>, R/N)', S1(53)+' — utilization']},
{id:'D3', set:'D', page:'12', ch:'2', type:'mcq', also:'7',
 q:`What is the role of an <b>authoritative name server</b> in the DNS?`,
 opts:['It is a local (to the querying host) server that caches name-to-IP address translation pairs, so it can answer authoritatively and can do so quickly.','It provides the definitive answer to the query with respect to a name in the authoritative name server\'s domain.','It provides the IP address of the DNS server that can provide the definitive answer to the query.','It provides a list of TLD servers that can be queried to find the IP address of the DNS server that can provide the definitive answer to this query.'],
 ans:1,
 exp:`Authoritative servers are an organization's own DNS servers and hold the official hostname-to-IP mappings for that organization's hosts. Option A describes a local DNS server, C a TLD server, D a root server.`,
 src:[S2(49)+' — authoritative DNS servers', S2(46)+' — DNS hierarchy']},
{id:'D4', set:'D', page:'13', ch:'1', type:'mcq', also:'41',
 q:`An internet <b>router</b> involves the following layers of the TCP/IP layers:`,
 opts:['Physical and data link layers','Application, transport and network layers','Transport, network and physical layers','Network, data link and physical layers'],
 ans:3,
 exp:`Routers implement the bottom three layers: network (IP forwarding), link and physical.`,
 note:`On PDF page 41 the selected answer is "Application, transport and network layers". That is wrong.`,
 src:[S1(69)+' — router: network / link / physical']},
{id:'D5a', set:'D', page:'14', ch:'1', type:'written', fig:'hostab', also:'30, 40',
 q:THREE_LINK+`<br><br>(a) Propagation delay of <b>link 2</b> = ? seconds`,
 answer:`d<sub>prop</sub> = 5×10<sup>6</sup> m / 2×10<sup>8</sup> m/s = <b>0.025 s</b>`,
 exp:`Link 2 is 5000 km long. Only length and speed matter for propagation delay.`,
 src:[S1(50)+' — d<sub>prop</sub> = d/s']},
{id:'D5b', set:'D', page:'14', ch:'1', type:'written', fig:'hostab', also:'30, 40',
 q:`(Same setup.) (b) What is the <b>total delay of link 2</b>? (seconds)`,
 answer:`4000 / 30×10<sup>6</sup> + 0.025 = 0.000133 + 0.025 = <b>0.025133 s</b> (≈ 0.02513)`,
 exp:`Transmission onto the 30 Mbps link plus propagation along it. No processing or queueing delay is given.`,
 src:[S1(49)+', '+S1(50).replace('Chapter 1 slides · ','')+' — the four delay components']},
{id:'D5c', set:'D', page:'14', ch:'1', type:'written', fig:'hostab', also:'30',
 q:`(Same setup.) (c) What is the <b>maximum throughput</b> that can be achieved from A to B?`,
 answer:`min(10, 30, 25) Mbps = <b>10 Mbps</b>`,
 exp:`Throughput is limited by the bottleneck link, here link 1 at 10 Mbps.`,
 note:`On PDF page 30 the box shows 0.0133. That is wrong: it is a traffic-intensity-style number, not a throughput.`,
 src:[S1(57)+' — bottleneck link', S1(58)+' — min of link rates']},
{id:'D6', set:'D', page:'15', ch:'1', type:'match', fig:'headers', also:'22',
 q:`The figure shows a link-layer frame heading from a host to a router, with three header fields H<sub>1</sub> H<sub>2</sub> H<sub>3</sub> in front of the message M. Match each header with its layer.`,
 rows:['Header H1','Header H2','Header H3'],
 choices:['A. Transport layer','B. Network layer','C. Link layer','D. Application layer','E. Physical layer'],
 ans:[2,1,0],
 answer:`H1 → C. Link · H2 → B. Network · H3 → A. Transport`,
 exp:`Encapsulation adds headers from the inside out: transport adds H<sub>t</sub> to M, network adds H<sub>n</sub> in front of that, and link adds H<sub>l</sub> outermost. A frame therefore reads H<sub>l</sub> H<sub>n</sub> H<sub>t</sub> M, so H1 is the link header and H3, the one next to M, is the transport header.`,
 note:`On PDF page 22 the saved choices are D, A, B. Those are wrong; the application layer adds no header in this figure.`,
 src:[S1(67)+' — link-layer frame [H<sub>l</sub> | H<sub>n</sub> | H<sub>t</sub> | M]', S1(68)+' — message, segment, datagram, frame']},
{id:'D7', set:'D', page:'16', ch:'2', type:'mcq', also:'11, 23, 24',
 q:`An HTTP/1.0 (non-persistent) client requests a base object from gaia.cs.umass.edu. It has never requested this object and has not communicated with the server recently, but it knows the server's IP address.<br><br>How many RTTs are needed from when the client first makes the request until the base page is completely downloaded, assuming the server needs <b>1/2 RTT to transmit the base file</b> into its link and the HTTP GET takes zero time to transmit? (Include TCP setup, the server's transmission time, and any propagation delays.)`,
 opts:['0 RTT','0.5 RTT','1.5 RTT','2.5 RTT','3.5 RTT'], ans:3,
 exp:`1 RTT for the TCP handshake + 1 RTT for the GET to reach the server and the first bits of the reply to come back + 0.5 RTT for the server to push the rest of the file = <b>2.5 RTT</b>. No DNS lookup is needed because the IP address is known.`,
 src:[S2(23)+' — non-persistent HTTP response time = 2RTT + file transmission time']},
{id:'D8', set:'D', page:'17', ch:'1', type:'mcq', also:'7, 39',
 q:`In circuit switching, a physical link can be shared among multiple users via:`,
 opts:['FDM and TDM','Packet switching','Wi-Fi and 4G','None of the above'], ans:0,
 exp:`A circuit-switched link is divided into circuits using frequency bands (FDM) or time slots (TDM).`,
 src:[S1(34)+' — Circuit switching: FDM and TDM']},

/* ================= SET E ================= */
{id:'E1', set:'E', page:'19', ch:'1', type:'mcq', also:'39',
 q:`The amount of time required to push all of the packet's bits into the link is the:`,
 opts:['propagation delay','queuing delay','transmission delay','end-to-end delay'], ans:2,
 exp:`Transmission delay = L/R: the time to push (transmit) an L-bit packet into a link of rate R.`,
 src:[S1(29)+' — "time needed to transmit L-bit packet into link"', S1(30)+' — "takes L/R seconds to transmit (push out) L-bit packet"']},
{id:'E2', set:'E', page:'31', ch:'2', type:'mcq',
 q:`What is the purpose of the <i>If-Modified-Since</i> field in an HTTP GET request message?`,
 opts:['To indicate to the server that the server should replace this named object with the new version of the object attached to the GET, if the object has not been modified since the specified time.','To allow the server to indicate to the client that it (the client) should cache this object.','To inform the HTTP cache that it (the cache) should retrieve the full object from the server, and then cache it until the specified time.','To indicate to the server that the client has cached this object from a previous GET, and the time it was cached.','To indicate to the server that the client wishes to receive this object, and the time until which it will cache the returned object in the browser\'s cache.'],
 ans:3,
 exp:`In a conditional GET, the client puts the date of its cached copy in <code>If-modified-since</code>. The server then sends the object only if it changed after that date; otherwise it replies 304 Not Modified.`,
 src:[S2(41)+' — Conditional GET: "client: specify date of cached copy in HTTP request"']},
{id:'E3', set:'E', page:'20', ch:'1', type:'match',
 q:`Match each Internet layer with the unit of data exchanged among protocol entities at that layer.`,
 rows:['Application layer','Transport layer','Network layer','Link layer','Physical layer'],
 choices:['A. Segment','B. Message','C. Datagram','D. Bit','E. Frame'],
 ans:[1,0,2,4,3],
 answer:`Application → Message · Transport → Segment · Network → Datagram · Link → Frame · Physical → Bit`,
 exp:`The application sends a message M; transport wraps it into a segment; network into a datagram; link into a frame; the physical layer sends individual bits "on the wire".`,
 src:[S1(68)+' — message / segment / datagram / frame', S1(64)+' — physical: bits on the wire']},
{id:'E5', set:'E', page:'21', ch:'1', type:'mcq',
 q:`Packet switching is:`,
 opts:['More efficient than circuit switching in terms of the number of users that can be served','Suitable for real-time services','A dedicated end-to-end connection between two hosts','All of the above'], ans:0,
 exp:`Packet switching lets more users share a link (35 vs 10 in the slide example). It is not ideal for real-time services because congestion causes variable delay and loss, and a dedicated end-to-end connection describes circuit switching.`,
 src:[S1(35)+' — 35 users vs 10 users', S1(36)+' — excessive congestion possible; how to provide circuit-like behavior is "complicated"', S1(33)+' — circuit switching: dedicated resources']},
{id:'E7a', set:'E', page:'25', ch:'2', type:'match',
 q:`Match the function of a server to its type of DNS server in the DNS hierarchy.`,
 rows:['Provides authoritative hostname to IP mappings for an organization\'s named hosts.','Replies to a DNS query by a local host, by contacting other DNS servers to answer the query.','Responsible for a domain (e.g. *.com, *.edu); knows how to contact authoritative name servers.','Highest level of the DNS hierarchy; knows how to reach servers responsible for a given domain (e.g. *.com, *.edu).'],
 choices:['A. Authoritative DNS server','B. DNS root servers','C. Top Level Domain (TLD) servers','D. Local DNS server'],
 ans:[0,3,2,1],
 answer:`Authoritative mappings → A · Answers the local host → D · Responsible for a domain → C · Highest level → B`,
 exp:`Root servers sit at the top and point to TLD servers. TLD servers (.com, .edu …) point to each organization's authoritative servers. The local DNS server receives the host's query and resolves it through the hierarchy.`,
 src:[S2(46)+' — hierarchy: root, TLD, authoritative', S2(48)+' — root name servers', S2(49)+' — TLD and authoritative servers', S2(50)+' — local DNS name servers']},
{id:'E8', set:'E', page:'26', ch:'2', type:'mcq',
 q:`What information does the type <b>"A"</b> resource record hold in the DNS database?`,
 opts:['A name and the name of the SMTP server associated with that name.','An alias name and a true name for a server.','A hostname and an IP address.','A domain name and the name of the authoritative name server for that domain.'], ans:2,
 exp:`type=A: name is a hostname, value is its IP address. The other options describe MX, CNAME and NS records.`,
 src:[S2(54)+' — DNS records']},
{id:'E7b', set:'E', page:'27', ch:'2', type:'mcq',
 q:`A client sends this HTTP GET request to gaia.cs.umass.edu:`,
 code:`GET /kurose_ross_sandbox/interactive/quotation2.htm HTTP/1.1
Host: gaia.cs.umass.edu
Accept: text/plain, text/html, text/xml, image/jpeg, image/gif, audio/mpeg, audio/mp4, video/wmv, video/mp4,
Accept-Language: en-us, en-gb;q=0.1, en;q=0.7, fr, fr-ch, da, de, fi
If-Modified-Since: Wed, 09 Sep 2020 16:06:01 -0700
User Agent: Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/535.11 (KHTML, like Gecko) Chrome/17.0.963.56 Safari/535.11`,
 q2:`Does the client have a cached copy of the object being requested?`,
 opts:['There\'s not enough information in the header to answer this question.','No, because a client would not request an object if it had that object in its cache.','Yes, because this is a conditional GET, as evidenced by the If-Modified-Since field.','Yes, because HTTP 1.1 is being used.'], ans:2,
 exp:`A client only sends If-Modified-Since when it already holds a cached copy and wants to know whether it is still up to date.`,
 src:[S2(41)+' — Conditional GET']},

/* ================= SET F ================= */
{id:'F1a', set:'F', page:'32', ch:'1', type:'written', fig:'servers4',
 q:`(a) What is the maximum achievable end-to-end throughput (in Mbps) for each of the four client-to-server pairs, assuming the middle link is fairly shared?`,
 answer:`min(R<sub>S</sub>, R<sub>C</sub>, R/4) = min(50, 90, 300/4 = 75) = <b>50 Mbps</b>`,
 exp:`With 4 connections sharing the middle link fairly, each gets R/4. The per-connection throughput is the smallest rate on its path.`,
 note:`This paper's figure is not in the PDF. The questions describe four servers, four clients and R<sub>S</sub> links to an upper router, which matches the four-server figure used elsewhere in the pack (R<sub>S</sub> = 50, R = 300, R<sub>C</sub> = 90 Mbps), so those numbers are used here. If your figure had different numbers, use the same formula.`,
 src:[S1(58)+' — per-connection end-end throughput: min(R<sub>c</sub>, R<sub>s</sub>, R/10) for 10 connections']},
{id:'F1b', set:'F', page:'32', ch:'1', type:'written', fig:'servers4',
 q:`(b) Which link is the bottleneck link?`,
 answer:`<b>The server links R<sub>S</sub> (50 Mbps)</b>`,
 exp:`R<sub>S</sub> = 50 Mbps is lower than the fair share of the middle link (75 Mbps) and the client links (90 Mbps), so it is the link that limits each connection.`,
 note:`Same assumption as part (a).`,
 src:[S1(57)+' — bottleneck link: the link that constrains end-end throughput', S1(58)+' — "in practice: R<sub>c</sub> or R<sub>s</sub> is often bottleneck"']},
{id:'F1c', set:'F', page:'32', ch:'1', type:'written', fig:'servers4',
 q:`(c) A file of size <b>400 M…</b> (unit partly hidden in the scan) needs to be transmitted from a server to the upper router through the R<sub>S</sub> link. Calculate the transmission delay at R<sub>S</sub>.`,
 answer:`If the file is 400 Mbits: d<sub>trans</sub> = L/R = 400×10<sup>6</sup> / 50×10<sup>6</sup> = <b>8 s</b>`,
 exp:`Transmission delay is file size in bits divided by the link rate. Always convert to bits first.`,
 note:`The unit is covered in the photo. If it is 400 MB (megabytes), L = 3200 Mbits and d<sub>trans</sub> = 3200 / 50 = 64 s. Assumes R<sub>S</sub> = 50 Mbps as in part (a).`,
 src:[S1(50)+' — d<sub>trans</sub> = L/R']},
{id:'F2-1', set:'F', page:'32', ch:'2', type:'mcq',
 q:`A generic error code indicating that the request could not be understood by the server.`,
 opts:['301','400','505','404'], ans:1,
 exp:`400 Bad Request: request message not understood by the server.`,
 src:[S2(29)+' — HTTP response status codes']},
{id:'F2-2', set:'F', page:'32', ch:'2', type:'mcq',
 q:`Internet telephony, to be effective, requires:`,
 opts:['Low delay','No loss','Encryption','None of the above'], ans:0,
 exp:`The slides give Internet telephony as the example of an app that needs low delay to be "effective". Real-time audio is loss-tolerant, so "no loss" is wrong.`,
 src:[S2(12)+' — timing: "some apps (e.g., Internet telephony, interactive games) require low delay to be effective"', S2(13)+' — real-time audio/video: loss-tolerant, time sensitive']},
{id:'F2-3', set:'F', page:'32', ch:'2', type:'mcq',
 q:`At most one object sent over a TCP connection. Connection then closed. Multiple connections to download multiple objects.`,
 opts:['Non-Persistent HTTP','Persistent HTTP','Conditional GET','None of the above'], ans:0,
 exp:`This is the slide's definition of non-persistent HTTP word for word.`,
 src:[S2(20)+' — HTTP connections: two types']},
{id:'F2-4', set:'F', page:'32', ch:'2', type:'mcq',
 q:`What is the correct type for the DNS resource record (networkutopia.com, dns1.networkutopia.com, ?)`,
 opts:['A','MX','NS','CNAME'], ans:2,
 exp:`The name is a domain and the value is the hostname of its authoritative name server, which is an NS record. This exact record appears on the slides.`,
 src:[S2(57)+' — (networkutopia.com, dns1.networkutopia.com, NS)', S2(54)+' — type=NS']},
{id:'F2-5', set:'F', page:'33', ch:'2', type:'mcq',
 q:`By using Web caching ______.`,
 opts:['it is possible to reduce response time for client request','it is possible to reduce traffic on an institution\'s access link','the cache acts as both client and server','All of the above responses are correct'], ans:3,
 exp:`All three statements are on the same slide: the cache is a server to the browser and a client to the origin server, and caching reduces both response time and access-link traffic.`,
 src:[S2(36)+' — Web caches (aka proxy servers)']},
{id:'F2-6', set:'F', page:'33', ch:'2', type:'mcq',
 q:`______ is a program running within a host.`,
 opts:['Protocol','Socket','Process','Identifier'], ans:2,
 exp:`"process: program running within a host." A socket is the door a process uses to send and receive messages.`,
 src:[S2(8)+' — Processes communicating', S2(9)+' — Sockets']},
{id:'F3-1', set:'F', page:'33', ch:'2', type:'written',
 q:`You want to retrieve a Web document at a given URL. The IP address of the URL is initially unknown (not cached in your local host).<br><br>1) What are the application-layer protocols needed in this scenario?`,
 answer:`<b>DNS</b> (to translate the hostname to an IP address) and <b>HTTP</b> (to request and receive the Web document)`,
 exp:`The host first resolves the name with DNS, then opens a TCP connection to the server and uses HTTP to fetch the page. Both are application-layer protocols.`,
 src:[S2(43)+' — DNS: application-layer protocol for name/address translation', S2(18)+' — HTTP: the Web\'s application-layer protocol']},
{id:'F3-2', set:'F', page:'33', ch:'2', type:'written',
 q:`2) Suppose 3 DNS servers are visited before your host receives the IP address from DNS, with RTTs of RTT<sub>1</sub>, RTT<sub>2</sub> and RTT<sub>3</sub>. The Web page contains exactly one small HTML object. RTT<sub>0</sub> is the RTT between the local host and the server containing the object. Assuming zero transmission time, how much time elapses from the click until the client receives the object?`,
 answer:`RTT<sub>1</sub> + RTT<sub>2</sub> + RTT<sub>3</sub> + <b>2·RTT<sub>0</sub></b>`,
 exp:`The DNS lookup takes the sum of the three DNS RTTs. Then HTTP takes one RTT<sub>0</sub> to set up the TCP connection and one RTT<sub>0</sub> to send the request and receive the object.`,
 src:[S2(51)+' — DNS name resolution visits several servers', S2(23)+' — HTTP response time = 2RTT + transmission time']},

/* ================= SET H ================= */
{id:'H1', set:'H', page:'37', ch:'1', type:'mcq',
 q:`The amount of data that can be transferred from one location to another in a given amount of time is called:`,
 opts:['Bandwidth','Speed','Throughput','Transmission Rate'], ans:0,
 exp:`"Can be transferred" describes capacity, which is the link's bandwidth. Throughput is the rate actually achieved between sender and receiver.`,
 note:`The slides use "link transmission rate, aka link capacity, aka link bandwidth" as one idea, so "Transmission Rate" is close. The answer selected on the scan (Bandwidth) is the standard textbook term for this definition.`,
 src:[S1(29)+' — "link transmission rate, aka link capacity, aka link bandwidth"', S1(3)+' — "transmission rate: bandwidth"', S1(56)+' — throughput = rate bits are actually sent']},
{id:'H2', set:'H', page:'37', ch:'1', type:'mcq',
 q:`In a circuit-switched TDM network with 5 users and bit rate R, each circuit has transmission rate:`,
 opts:['R/5','R','5R','R/10'], ans:0,
 exp:`TDM divides time into 5 slots, one per user. Each user transmits at the full rate R but only 1/5 of the time, so its average rate is R/5.`,
 src:[S1(34)+' — TDM: each call allocated periodic slot(s)', 'Tutorial 1 · Chapter 1, Q4a (circuit switching with 10 TDM slots: rate per circuit = 9600/10)']},
{id:'H3a', set:'H', page:'38', ch:'1', type:'written', fig:'hostab',
 q:THREE_LINK+`<br><br>(a) Propagation delay of <b>link 3</b> = ? seconds`,
 answer:`1×10<sup>6</sup> m / 2×10<sup>8</sup> m/s = <b>0.005 s</b>`,
 exp:`Link 3 is 1000 km = 10<sup>6</sup> m long.`,
 src:[S1(50)+' — d<sub>prop</sub> = d/s']},
{id:'H3b', set:'H', page:'38', ch:'1', type:'written', fig:'hostab',
 q:`(Same setup.) (b) What is the <b>total delay of link 3</b>? (seconds)`,
 answer:`4000 / 25×10<sup>6</sup> + 0.005 = 0.00016 + 0.005 = <b>0.00516 s</b>`,
 exp:`Transmission delay onto the 25 Mbps link plus propagation along it.`,
 src:[S1(49)+', '+S1(50).replace('Chapter 1 slides · ','')+' — the four delay components']},
{id:'H3c', set:'H', page:'38', ch:'1', type:'written', fig:'hostab', also:'40',
 q:`(Same setup.) (c) If the average packet arrival rate at <b>Router 2</b> is <b>100 packets/s</b>, compute the traffic intensity at Router 2.`,
 answer:`La/R = (100 × 4000) / 25×10<sup>6</sup> = <b>0.016</b>`,
 exp:`Router 2 queues packets for its output link toward Host B, which is link 3 at 25 Mbps.`,
 note:`On PDF page 40 the box shows 0.0133, which is what you get using link 2's 30 Mbps. Link 2 brings packets <i>into</i> Router 2, so it is not the link Router 2 queues for.`,
 src:[S1(53)+' — traffic intensity = La/R', S1(31)+' — queue waiting for transmission over output link']},
{id:'H4', set:'H', page:'42', ch:'1', type:'mcq',
 q:`The difference between TDM and FDM:`,
 opts:['TDM uses time while FDM uses frequency for splitting','FDM uses time while TDM uses frequency for splitting','FDM is for packet switching while TDM for circuit switching','None of above'], ans:0,
 exp:`TDM divides time into slots; FDM divides the spectrum into frequency bands. Both are circuit-switching techniques.`,
 src:[S1(34)+' — FDM and TDM']},

/* ================= SET G (beyond slides) ================= */
{id:'G1-1', set:'G', page:'34', ch:'x', type:'mcq',
 q:`What is the primary function of the network layer?`,
 opts:['To provide end-to-end processes communication','To deliver packets from the source to the destination.','To establish a connection between applications','To ensure reliable data transfer'], ans:1,
 exp:`The network layer moves datagrams from source host to destination host. Process-to-process delivery and reliability belong to the transport layer.`,
 src:[S1(64)+' — "network: routing of datagrams from source to destination"']},
{id:'G1-2', set:'G', page:'34', ch:'x', type:'mcq',
 q:`What is a major difference between IPv4 and IPv6?`,
 opts:['IPv4 uses a 32-bit address; IPv6 uses a 128-bit address.','IPv4 is more secure than IPv6.','IPv4 supports more devices than IPv6.','IPv4 does not support fragmentation.'], ans:0,
 exp:`IPv6 was created mainly because 32-bit IPv4 addresses were running out; it uses 128-bit addresses.`,
 src:[S2(10)+' — "host device has unique 32-bit IP address" (IPv4)', OUT+', §4.3.4 IPv6']},
{id:'G1-3', set:'G', page:'34', ch:'x', type:'mcq',
 q:`What mechanism does the network layer use to handle data packets that are too large for the underlying data link layer?`,
 opts:['Encapsulation','Segmentation','Fragmentation','Aggregation'], ans:2,
 exp:`When a datagram is larger than the link's MTU, IPv4 splits it into fragments that are reassembled at the destination. Segmentation is what the transport layer does to application data.`,
 src:[OUT+', §4.3.1 IPv4 datagram format (fragmentation)']},
{id:'G1-4', set:'G', page:'34', ch:'x', type:'mcq',
 q:`A datagram with destination IP address <b>10.1.1.10</b> arrives at a router. Which entry will the router use to route it?`,
 opts:['10.0.0.0/8','10.1.0.0/16','10.1.1.0/24'], ans:2,
 exp:`All three prefixes match 10.1.1.10. Routers use <b>longest prefix matching</b>, so the most specific entry wins: /24.`,
 src:[OUT+', §4.2.1 longest prefix matching']},
{id:'G1-5', set:'G', page:'34', ch:'x', type:'mcq',
 q:`Which of the following is the correct definition of tunneling?`,
 opts:['IPv4 datagram carried as payload in IPv6 datagram among IPv4 routers.','IPv6 datagram carried as payload in IPv4 datagram among IPv4 routers.','IPv4 datagram carried as payload in IPv6 datagram among IPv6 routers.','IPv4 datagram carried as payload in other IPv4 datagram among IPv4 routers.'], ans:1,
 exp:`Tunneling lets IPv6 traffic cross a part of the network that only understands IPv4: the whole IPv6 datagram is put inside an IPv4 datagram's payload.`,
 src:[OUT+', §4.3.4 transitioning from IPv4 to IPv6 (tunneling)']},
{id:'G1-6', set:'G', page:'34', ch:'x', type:'mcq',
 q:`Which IP header field is used to avoid an endless loop of the datagram within the networks?`,
 opts:['Upper layer','Source IP Address','Destination IP Address','Time to live TTL','Type of service'], ans:3,
 exp:`Each router decrements TTL; when it reaches 0 the datagram is dropped, so a datagram can't circulate forever. Chapter 1's traceroute slide relies on the same field.`,
 src:[S1(54)+' — traceroute uses the time-to-live field', OUT+', §4.3.1']},

{id:'G2-1', set:'G', page:'35', ch:'x', type:'written', fig:'tcp',
 q:`The figure shows TCP congestion control for TCP Reno and TCP Tahoe (fast recovery not used).<br><br>1) Identify the intervals of time when <b>slow start</b> is operating for TCP <b>Reno</b>.`,
 answer:`<b>Rounds 1 to 4</b> (cwnd 1 → 2 → 4 → 8)`,
 exp:`In slow start cwnd doubles every round. It reaches ssthresh = 8 at round 4, then grows by one segment per round. After the loss at round 8, Reno's line restarts at the new threshold (6) and grows linearly, so Reno does not enter slow start again in this figure.`,
 src:[OUT+', §3.7.1 TCP congestion control (Figure 3.53 is this graph)']},
{id:'G2-2', set:'G', page:'35', ch:'x', type:'written', fig:'tcp',
 q:`2) Identify the intervals of time when <b>congestion avoidance</b> is operating for TCP <b>Tahoe</b>.`,
 answer:`<b>Rounds 4 to 8</b> and <b>rounds 12 to 15</b>`,
 exp:`From round 4 (cwnd = ssthresh = 8) to the loss at round 8, cwnd grows linearly. After the loss Tahoe drops to 1 and slow-starts (1, 2, 4) until it reaches the new ssthresh of 6 at round 12, then grows linearly again.`,
 src:[OUT+', §3.7.1']},
{id:'G2-3', set:'G', page:'35', ch:'x', type:'written', fig:'tcp',
 q:`3) What is the value of the congestion window for TCP <b>Reno</b> at transmission round 7?`,
 answer:`<b>11 segments</b>`,
 exp:`8 at round 4, then +1 per round: 9, 10, 11 at round 7 (and 12 at round 8, where the loss happens).`,
 src:[OUT+', §3.7.1']},
{id:'G2-4', set:'G', page:'35', ch:'x', type:'written', fig:'tcp',
 q:`4) What is the value of the congestion window for TCP <b>Tahoe</b> at transmission round 11?`,
 answer:`<b>4 segments</b>`,
 exp:`Tahoe restarts at 1 in round 9, doubles to 2 in round 10 and 4 in round 11.`,
 src:[OUT+', §3.7.1']},
{id:'G2-5', set:'G', page:'35', ch:'x', type:'written', fig:'tcp',
 q:`5) What is the value of ssthresh at T = 1 for TCP <b>Reno</b>?`,
 answer:`<b>8</b>`,
 exp:`The initial threshold is the dashed line at 8: slow start stops and linear growth begins when cwnd reaches 8.`,
 src:[OUT+', §3.7.1']},
{id:'G2-6', set:'G', page:'35', ch:'x', type:'written', fig:'tcp',
 q:`6) What is the value of ssthresh at T = 9 for TCP <b>Tahoe</b>?`,
 answer:`<b>6</b>`,
 exp:`On loss, ssthresh is set to half of cwnd. cwnd was 12 when the loss happened in round 8, so ssthresh = 12 / 2 = 6 (the lower dashed line).`,
 src:[OUT+', §3.7.1']},

{id:'G3a', set:'G', page:'35', ch:'x', type:'written',
 q:`An organization is granted the block <b>230.10.0.0/24</b>. The administrator wants to create <b>2 subnets</b>. (Write IP addresses in dotted-decimal notation.)<br><br>a) Find the subnet mask.`,
 answer:`Borrow 1 bit → /25 → <b>255.255.255.128</b>`,
 exp:`2 subnets need log<sub>2</sub>2 = 1 extra network bit, so the prefix goes from /24 to /25. The last octet becomes 1000 0000 = 128.`,
 note:`The number of subnets is cut off in the photo; the table on the next page has Subnet 1 and Subnet 2, so 2 subnets is used.`,
 src:[OUT+', §4.3.3 IPv4 addressing (CIDR, subnets)']},
{id:'G3b', set:'G', page:'35', ch:'x', type:'written',
 q:`b) Find the total number of IP addresses in each subnet.`,
 answer:`2<sup>32−25</sup> = 2<sup>7</sup> = <b>128 addresses</b>`,
 exp:`7 host bits remain, giving 128 addresses per subnet.`,
 src:[OUT+', §4.3.3']},
{id:'G3c', set:'G', page:'36', ch:'x', type:'written',
 q:`c) Find the number of hosts in each subnet.`,
 answer:`128 − 2 = <b>126 hosts</b>`,
 exp:`The all-zeros address (network) and all-ones address (broadcast) cannot be given to hosts.`,
 src:[OUT+', §4.3.3']},
{id:'G3d', set:'G', page:'36', ch:'x', type:'written',
 q:`d) For each subnet find the network address, broadcast address, first host and last host.`,
 answer:`<table class="mini"><tr><th></th><th>Subnet 1</th><th>Subnet 2</th></tr>
<tr><td>Network address</td><td>230.10.0.0</td><td>230.10.0.128</td></tr>
<tr><td>Broadcast address</td><td>230.10.0.127</td><td>230.10.0.255</td></tr>
<tr><td>First host</td><td>230.10.0.1</td><td>230.10.0.129</td></tr>
<tr><td>Last host</td><td>230.10.0.126</td><td>230.10.0.254</td></tr></table>`,
 exp:`Each /25 block holds 128 addresses: 0–127 and 128–255 in the last octet. The first host is network + 1 and the last host is broadcast − 1.`,
 src:[OUT+', §4.3.3']},

{id:'G4', set:'G', page:'36', ch:'x', type:'written',
 q:`An organization has the private block 192.168.1.0/24 and one public IP address <b>132.85.10.20</b> (port 5000 used) on its NAT router. Host <b>192.168.1.2</b>, port <b>1000</b>, requests a Web page from Web server <b>220.70.10.60</b>. Show the source and destination [IP address, port] for the request and response, inside and outside the NAT.`,
 answer:`<table class="mini"><tr><th></th><th>Source</th><th>Destination</th></tr>
<tr><td>Request inside LAN</td><td>192.168.1.2, 1000</td><td>220.70.10.60, 80</td></tr>
<tr><td>Request outside LAN</td><td>132.85.10.20, 5000</td><td>220.70.10.60, 80</td></tr>
<tr><td>Response outside LAN</td><td>220.70.10.60, 80</td><td>132.85.10.20, 5000</td></tr>
<tr><td>Response inside LAN</td><td>220.70.10.60, 80</td><td>192.168.1.2, 1000</td></tr></table>`,
 exp:`The NAT router replaces the private source (192.168.1.2, 1000) with its public address and a new port (132.85.10.20, 5000), and records the pair in its translation table. Replies come back to 132.85.10.20:5000 and are translated back to 192.168.1.2:1000. Web servers listen on port 80.`,
 src:[S2(10)+' — HTTP server port number: 80', OUT+', §4.3.4 Network Address Translation']}
];
